import { Router } from 'express';
import { autoGenerateDomTests, autoGenerateStyleTests } from '../utils/autoGenerateTests.js';
import { buildPage } from '../worker/pageBuilder.js';
import { bundleFiles } from '../worker/bundler.js';
import { normalizeAllowedDomains, resolveAllowedDomains } from '../worker/networkPolicy.js';
import { captureBaseline } from '../worker/baselineCapture.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import {
  getMainFile,
  mergeFilesByType,
  ProjectFilesError,
  validateAndNormalizeFiles
} from '../utils/projectFiles.js';

const router = Router();

// POST /api/assignments — teacher creates assignment
router.post('/', requireAuth, requireRole('teacher'), async (req, res) => {
  const {
    title,
    description,
    files: incomingFiles,
    functionalityTests,
    interactionTests,
    allowedCdnDomains = [],
    allowedLibraryPolicyIds = [],
    viewports = ['desktop'],
    timeoutMs = 30000,
    groupIds = []
  } = req.body;
  if (!title?.trim()) return res.status(400).json({ error: 'title is required' });

  const { Assignment, LibraryPolicy } = req.db;

  let normalized;
  try {
    normalized = validateAndNormalizeFiles(incomingFiles || req.body);
  } catch (err) {
    if (err instanceof ProjectFilesError) {
      return res.status(err.status).json({ error: err.message, details: err.details || [] });
    }
    throw err;
  }

  const mainHtml  = getMainFile(normalized.files, 'html');
  const mergedCss = mergeFilesByType(normalized.files, 'css');
  const domTests  = autoGenerateDomTests(mainHtml?.content || '');
  const styleTests = autoGenerateStyleTests(mainHtml?.content || '', mergedCss);

  const fnTests  = Array.isArray(functionalityTests) ? functionalityTests : [];
  const intTests = Array.isArray(interactionTests)   ? interactionTests   : [];
  const normalizedAllowedCdnDomains = normalizeAllowedDomains(allowedCdnDomains);
  const effectiveAllowedDomains     = resolveAllowedDomains(normalizedAllowedCdnDomains);
  const policyIds = Array.isArray(allowedLibraryPolicyIds) ? allowedLibraryPolicyIds : [];

  const activePolicies = policyIds.length > 0
    ? await LibraryPolicy.find({ _id: { $in: policyIds }, enabled: true })
    : [];
  const effectiveUrlPrefixes = activePolicies.flatMap(p => p.cdnUrls || []);

  const assignment = await Assignment.create({
    title,
    description: description || '',
    createdBy:   req.user.id,
    industryId:  req.user.industryId,
    groupIds:    Array.isArray(groupIds) ? groupIds : [],
    files:       normalized.files,
    allowedCdnDomains: normalizedAllowedCdnDomains,
    allowedLibraryPolicyIds: policyIds,
    evalSpec: {
      domTests,
      styleTests,
      interactionTests: intTests,
      functionalityTests: fnTests,
      viewports: Array.isArray(viewports) && viewports.length > 0 ? viewports : ['desktop'],
      timeoutMs: Number(timeoutMs) > 0 ? Number(timeoutMs) : 30000
    }
  });

  let referenceScreenshotUrl = null;
  let referenceScreenshots   = [];
  let referencePageScreenshots = [];

  try {
    const { pageFilePaths, bundle } = await buildPage(`baseline-${assignment._id}`, normalized.files);
    const result = await captureBaseline({
      bundle,
      pageFilePaths,
      assignmentId:  assignment._id,
      industrySlug:  req.user.industrySlug,
      viewportNames: Array.isArray(viewports) && viewports.length > 0 ? viewports : ['desktop'],
      allowedDomains:     effectiveAllowedDomains,
      allowedUrlPrefixes: effectiveUrlPrefixes
    });
    referenceScreenshotUrl   = result.referenceScreenshotUrl;
    referenceScreenshots     = result.referenceScreenshots;
    referencePageScreenshots = result.referencePageScreenshots;

    await Assignment.findByIdAndUpdate(assignment._id, {
      referenceScreenshotUrl,
      referenceScreenshots,
      referencePageScreenshots,
      baselineGeneratedAt: new Date()
    });
  } catch (err) {
    console.error('Baseline capture failed:', err.message);
  }

  return res.status(201).json({
    assignmentId: assignment._id,
    title:        assignment.title,
    fileCount:    normalized.files.length,
    warnings:     normalized.warnings,
    testsGenerated: {
      dom: domTests.length, style: styleTests.length,
      functionality: fnTests.length, interaction: intTests.length
    },
    referenceScreenshotUrl,
    referenceScreenshots,
    referencePageScreenshots,
    allowedCdnDomains: normalizedAllowedCdnDomains,
    screenshotCount: referenceScreenshots.length
  });
});

// GET /api/assignments — list active assignments visible to the caller
router.get('/', requireAuth, async (req, res) => {
  const { Assignment, Group } = req.db;
  const filter = { isActive: true, industryId: req.user.industryId };

  // Students only see assignments whose groupIds include one of their groups
  if (req.user.role === 'student') {
    const myGroups = await Group.find({ studentIds: req.user.id }).select('_id');
    const myGroupIds = myGroups.map(g => g._id.toString());
    filter.groupIds = myGroupIds.length > 0 ? { $in: myGroupIds } : { $in: [] };
  }

  const assignments = await Assignment.find(filter)
    .select('_id title description referenceScreenshotUrl referenceScreenshots referencePageScreenshots allowedCdnDomains createdBy createdAt groupIds files')
    .sort({ createdAt: -1 });
  return res.json(assignments);
});

// GET /api/assignments/:id — full detail
router.get('/:id', requireAuth, async (req, res) => {
  const assignment = await req.db.Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });
  return res.json(assignment);
});

// PATCH /api/assignments/:id — teacher updates tests/domains
router.patch('/:id', requireAuth, requireRole('teacher'), async (req, res) => {
  const { functionalityTests, interactionTests, allowedCdnDomains, allowedLibraryPolicyIds, groupIds } = req.body;
  const update = {};
  if (Array.isArray(functionalityTests))    update['evalSpec.functionalityTests'] = functionalityTests;
  if (Array.isArray(interactionTests))      update['evalSpec.interactionTests']   = interactionTests;
  if (Array.isArray(allowedCdnDomains))     update.allowedCdnDomains = normalizeAllowedDomains(allowedCdnDomains);
  if (Array.isArray(allowedLibraryPolicyIds)) update.allowedLibraryPolicyIds = allowedLibraryPolicyIds;
  if (Array.isArray(groupIds))              update.groupIds = groupIds;

  if (Object.keys(update).length === 0)
    return res.status(400).json({ error: 'Nothing to update' });

  const assignment = await req.db.Assignment.findByIdAndUpdate(
    req.params.id, { $set: update }, { new: true }
  );
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });

  return res.json({
    assignmentId: assignment._id,
    functionalityTests: assignment.evalSpec.functionalityTests.length,
    interactionTests:   assignment.evalSpec.interactionTests.length,
    allowedCdnDomains:  assignment.allowedCdnDomains || [],
    allowedLibraryPolicyIds: assignment.allowedLibraryPolicyIds || [],
    groupIds: assignment.groupIds || []
  });
});

// DELETE /api/assignments/:id
router.delete('/:id', requireAuth, requireRole('teacher'), async (req, res) => {
  const { Assignment, Submission, EvaluationRun, StudentProgress } = req.db;
  const assignment = await Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });

  const storedBy  = assignment.createdBy?.toString().trim();
  const requestBy = req.user.id?.toString().trim();
  if (storedBy !== requestBy)
    return res.status(403).json({ error: 'You do not own this assignment' });

  const submissions  = await Submission.find({ assignmentId: req.params.id }).select('submissionId');
  const submissionIds = submissions.map(s => s.submissionId);

  await Promise.all([
    submissionIds.length > 0 ? EvaluationRun.deleteMany({ submissionId: { $in: submissionIds } }) : null,
    Submission.deleteMany({ assignmentId: req.params.id }),
    StudentProgress.deleteMany({ assignmentId: req.params.id }),
    Assignment.findByIdAndUpdate(req.params.id, { isActive: false })
  ]);

  return res.json({
    success: true,
    message: 'Assignment and all associated submissions deleted.',
    deletedSubmissions: submissionIds.length
  });
});

// PATCH /api/assignments/:id/toggle
router.patch('/:id/toggle', requireAuth, requireRole('teacher'), async (req, res) => {
  const assignment = await req.db.Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });
  assignment.isActive = !assignment.isActive;
  await assignment.save();
  return res.json({ _id: assignment._id, isActive: assignment.isActive });
});

// PATCH /api/assignments/:id/library-policies
router.patch('/:id/library-policies', requireAuth, requireRole('teacher'), async (req, res) => {
  const { Assignment, LibraryPolicy } = req.db;
  const { policyIds } = req.body;
  if (!Array.isArray(policyIds)) return res.status(400).json({ error: 'policyIds must be an array' });

  const policies = policyIds.length > 0
    ? await LibraryPolicy.find({ _id: { $in: policyIds }, enabled: true })
    : [];

  const policyDomains = [];
  for (const policy of policies) {
    for (const cdnUrl of policy.cdnUrls || []) {
      try {
        const { hostname } = new URL(cdnUrl);
        if (hostname && !policyDomains.includes(hostname)) policyDomains.push(hostname);
      } catch { /* skip invalid URLs */ }
    }
  }

  const current = await Assignment.findById(req.params.id);
  if (!current) return res.status(404).json({ error: 'Assignment not found' });

  const mergedDomains = normalizeAllowedDomains([...(current.allowedCdnDomains || []), ...policyDomains]);
  const updated = await Assignment.findByIdAndUpdate(
    req.params.id,
    { $set: { allowedLibraryPolicyIds: policyIds, allowedCdnDomains: mergedDomains } },
    { new: true }
  );
  return res.json({
    assignmentId: updated._id,
    allowedLibraryPolicyIds: updated.allowedLibraryPolicyIds,
    allowedCdnDomains: updated.allowedCdnDomains
  });
});

// POST /api/assignments/:id/regenerate-baseline
router.post('/:id/regenerate-baseline', requireAuth, requireRole('teacher'), async (req, res) => {
  const { Assignment, LibraryPolicy } = req.db;
  const assignment = await Assignment.findById(req.params.id);
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });
  if (!assignment.files?.length) return res.status(400).json({ error: 'Assignment has no files' });

  const allowedDomains = resolveAllowedDomains(assignment.allowedCdnDomains);
  const policyIds      = assignment.allowedLibraryPolicyIds || [];
  const activePolicies = policyIds.length > 0
    ? await LibraryPolicy.find({ _id: { $in: policyIds }, enabled: true })
    : [];
  const allowedUrlPrefixes = activePolicies.flatMap(p => p.cdnUrls || []);

  try {
    const { pageFilePaths, bundle } = await buildPage(`baseline-${assignment._id}`, assignment.files);
    const viewportNames = assignment.evalSpec?.viewports?.length > 0
      ? assignment.evalSpec.viewports
      : ['desktop'];

    const { referenceScreenshotUrl, referenceScreenshots, referencePageScreenshots } =
      await captureBaseline({
        bundle, pageFilePaths, assignmentId: assignment._id,
        industrySlug: req.user.industrySlug,
        viewportNames, allowedDomains, allowedUrlPrefixes
      });

    await Assignment.findByIdAndUpdate(assignment._id, {
      referenceScreenshotUrl, referenceScreenshots, referencePageScreenshots,
      baselineGeneratedAt: new Date()
    });

    return res.json({ success: true, referenceScreenshotUrl, screenshotCount: referenceScreenshots.length });
  } catch (err) {
    console.error('Baseline regeneration failed:', err.message);
    return res.status(500).json({ error: 'Baseline regeneration failed: ' + err.message });
  }
});

// GET /api/assignments/:id/libraries
router.get('/:id/libraries', requireAuth, async (req, res) => {
  const { Assignment, LibraryPolicy } = req.db;
  const assignment = await Assignment.findById(req.params.id).select('allowedLibraryPolicyIds');
  if (!assignment) return res.status(404).json({ error: 'Assignment not found' });
  const policies = assignment.allowedLibraryPolicyIds?.length > 0
    ? await LibraryPolicy.find({ _id: { $in: assignment.allowedLibraryPolicyIds }, enabled: true })
    : [];
  return res.json(policies.map(p => ({ id: p._id, name: p.name, version: p.version, cdnUrls: p.cdnUrls })));
});

// GET /api/assignments/:id/preview
router.get('/:id/preview', requireAuth, async (req, res) => {
  const assignment = await req.db.Assignment.findById(req.params.id);
  if (!assignment || !assignment.isActive)
    return res.status(404).json({ error: 'Assignment not found' });

  let html;
  try {
    ({ html } = bundleFiles(assignment.files));
  } catch (err) {
    return res.status(422).json({ error: 'Could not bundle assignment files: ' + err.message });
  }
  const stripped = html.replace(/<!--[\s\S]*?-->/g, '');
  return res.json({ html: stripped });
});

// GET /api/assignments/:id/submissions — teacher: best per student
router.get('/:id/submissions', requireAuth, requireRole('teacher'), async (req, res) => {
  const { StudentProgress, Submission, EvaluationRun } = req.db;
  const progressRecords = await StudentProgress.find({ assignmentId: req.params.id });
  if (progressRecords.length === 0) return res.json([]);

  const bestSubmissionIds = progressRecords.filter(p => p.bestSubmissionId).map(p => p.bestSubmissionId);

  const [submissions, runs] = await Promise.all([
    Submission.find({ submissionId: { $in: bestSubmissionIds } }),
    EvaluationRun.find({ submissionId: { $in: bestSubmissionIds } })
  ]);

  const subMap = Object.fromEntries(submissions.map(s => [s.submissionId, s]));
  const runMap = Object.fromEntries(runs.map(r => [r.submissionId, r]));

  const results = progressRecords.map(p => {
    const sub = subMap[p.bestSubmissionId];
    const run = runMap[p.bestSubmissionId];
    return {
      submissionId: p.bestSubmissionId,
      studentId:    p.studentId,
      status:       sub?.status ?? (run ? 'done' : 'pending'),
      submittedAt:  sub?.submittedAt ?? null,
      attempts:     p.attempts,
      bestScore:    p.bestScore,
      completed:    p.completed,
      completedAt:  p.completedAt,
      result:       run || null
    };
  });

  results.sort((a, b) => {
    if (b.completed !== a.completed) return b.completed ? 1 : -1;
    return b.bestScore - a.bestScore;
  });

  return res.json(results);
});

export default router;
